### ISSUE TITLE
CHIBIOS SUPPORT FOR TELEMETRY ap 3.9.2

### ISSUE THREAD

**Issue by pegaxo** [yaapu/FrskyTelemetryScript#15]
After update to ChibiOS version of arduplane the ground data received to telemetry fail to display.

The telemetry start correctly but after some second the screen was blocked

**Comment by yaapu** [comment]
Hi, I don't think your issue is related to my script.
Regarding ChibiOS i regularly use:
- a Pixracer with ChibiOS Copter 3.6, 
- a Pixhawk 1 with ChibiOS Copter 3.6
- an omnibusf4v3 with ChibiOS plane 3.9.2,

an all but the pixracer i use a DIY max3232 inverter and frsky passthrough telemetry works just fine.

Alex.

**Comment by pegaxo** [comment]
Hy. in particular i use pixhawk1 fmuv3 with arduplane 3.9.2 over chibios, i'll upload some screen of the problem
